package http

import (
	"context"
	"errors"
	"fmt"
	"strconv"

	"github.com/Stoganet/api-proxy/internal/gen"
	"github.com/Stoganet/api-proxy/internal/media"
)

func (s *Server) GetLibraryId(ctx context.Context, req gen.GetLibraryIdRequestObject) (gen.GetLibraryIdResponseObject, error) { //nolint:revive // name generated by oapi-codegen
	userID := userIDFromCtx(ctx)
	jfUserID := jfUserIDFromCtx(ctx)

	jfTok, err := s.auth.GetJellyfinToken(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("GetJellyfinToken: %w", err)
	}

	d, err := s.library.GetItem(ctx, jfUserID, jfTok, req.Id)
	if err != nil {
		if errors.Is(err, media.ErrItemNotFound) {
			return gen.GetLibraryId404JSONResponse(apiError(ctx, gen.ItemNotFound, "item not found")), nil
		}
		return gen.GetLibraryId503JSONResponse(apiError(ctx, gen.BackendUnavailable, "upstream error")), nil
	}

	return gen.GetLibraryId200JSONResponse(toGenDetail(d)), nil
}

func (s *Server) GetLibrary(ctx context.Context, req gen.GetLibraryRequestObject) (gen.GetLibraryResponseObject, error) {
	jfUserID := jfUserIDFromCtx(ctx)

	opts := media.ListOpts{}
	if req.Params.Type != nil {
		opts.Type = string(*req.Params.Type)
	}
	if req.Params.Limit != nil {
		opts.Limit = *req.Params.Limit
	}
	if req.Params.Cursor != nil {
		n, err := strconv.Atoi(*req.Params.Cursor)
		if err != nil {
			return gen.GetLibrary400JSONResponse(apiError(ctx, gen.ValidationFailed, "cursor must be a numeric string")), nil //nolint:nilerr // error encoded in response
		}
		opts.StartIndex = n
	}

	result, err := s.library.List(ctx, jfUserID, opts)
	if err != nil {
		return gen.GetLibrary503JSONResponse(apiError(ctx, gen.BackendUnavailable, "upstream error")), nil //nolint:nilerr // error encoded in response
	}

	items := make([]gen.LibraryItem, len(result.Items))
	for i, it := range result.Items {
		items[i] = toGenItem(it)
	}

	var nextCursor *string
	if result.NextCursor != "" {
		nextCursor = &result.NextCursor
	}

	return gen.GetLibrary200JSONResponse(gen.LibraryListResponse{
		Items:      items,
		Total:      result.Total,
		NextCursor: nextCursor,
	}), nil
}

func toGenItem(it media.Item) gen.LibraryItem {
	var backdrop *string
	if it.Backdrop != "" {
		backdrop = &it.Backdrop
	}
	return gen.LibraryItem{
		Id:       it.ID,
		Title:    it.Title,
		Year:     it.Year,
		Type:     gen.MediaType(it.Type),
		Poster:   it.Poster,
		Backdrop: backdrop,
		Overview: it.Overview,
		State:    gen.MediaState(it.State),
	}
}

func toGenDetail(d *media.Detail) gen.LibraryDetail {
	cast := make([]gen.CastMember, len(d.Cast))
	for i, c := range d.Cast {
		cast[i] = gen.CastMember{Name: c.Name, Role: c.Role}
	}

	genres := d.Genres
	if genres == nil {
		genres = []string{}
	}

	var backdrop *string
	if d.Backdrop != "" {
		backdrop = &d.Backdrop
	}

	detail := gen.LibraryDetail{
		Id:       d.ID,
		Title:    d.Title,
		Year:     d.Year,
		Type:     gen.MediaType(d.Type),
		Poster:   d.Poster,
		Backdrop: backdrop,
		Overview: d.Overview,
		State:    gen.MediaState(d.State),
		Genres:   genres,
		Runtime:  d.Runtime,
		Cast:     cast,
		Seasons:  d.Seasons,
	}

	if d.Play != nil {
		detail.Play = &gen.PlayInfo{
			JellyfinItemId:      d.Play.JellyfinItemID,
			JellyfinBaseUrl:     d.Play.JellyfinBaseURL,
			JellyfinAccessToken: d.Play.JellyfinAccessToken,
			JellyfinUserId:      d.Play.JellyfinUserID,
		}
	}

	return detail
}

func userIDFromCtx(ctx context.Context) string {
	v, _ := ctx.Value(ctxUserID).(string)
	return v
}

func jfUserIDFromCtx(ctx context.Context) string {
	v, _ := ctx.Value(ctxJFUserID).(string)
	return v
}
