package http

import (
	"context"
	"errors"
	"strconv"

	"github.com/Stoganet/api-proxy/internal/gen"
	"github.com/Stoganet/api-proxy/internal/media"
)

func (s *Server) GetLibraryId(ctx context.Context, req gen.GetLibraryIdRequestObject) (gen.GetLibraryIdResponseObject, error) { //nolint:revive // name generated by oapi-codegen
	jfUserID := jfUserIDFromCtx(ctx)

	d, err := s.library.GetItem(ctx, jfUserID, req.Id)
	if err != nil {
		if errors.Is(err, media.ErrItemNotFound) {
			return gen.GetLibraryId404JSONResponse(apiError(ctx, gen.ItemNotFound, "item not found")), nil
		}
		return gen.GetLibraryId503JSONResponse(apiError(ctx, gen.BackendUnavailable, "upstream error")), nil
	}

	return gen.GetLibraryId200JSONResponse(toGenDetail(d)), nil
}

func (s *Server) GetLibrary(ctx context.Context, req gen.GetLibraryRequestObject) (gen.GetLibraryResponseObject, error) {
	jfUserID := jfUserIDFromCtx(ctx)

	opts := media.ListOpts{}
	if req.Params.Type != nil {
		opts.Type = media.Type(*req.Params.Type)
	}
	if req.Params.Limit != nil {
		opts.Limit = *req.Params.Limit
	}
	if req.Params.Cursor != nil {
		n, err := strconv.Atoi(*req.Params.Cursor)
		if err != nil {
			return gen.GetLibrary400JSONResponse(apiError(ctx, gen.ValidationFailed, "cursor must be a numeric string")), nil //nolint:nilerr // error encoded in response
		}
		opts.StartIndex = n
	}

	result, err := s.library.List(ctx, jfUserID, opts)
	if err != nil {
		return gen.GetLibrary503JSONResponse(apiError(ctx, gen.BackendUnavailable, "upstream error")), nil //nolint:nilerr // error encoded in response
	}

	items := make([]gen.LibraryItem, len(result.Items))
	for i, it := range result.Items {
		items[i] = toGenItem(it)
	}

	var nextCursor *string
	if result.NextCursor != "" {
		nextCursor = &result.NextCursor
	}

	return gen.GetLibrary200JSONResponse(gen.LibraryListResponse{
		Items:      items,
		Total:      result.Total,
		NextCursor: nextCursor,
	}), nil
}

func toGenItem(it media.Item) gen.LibraryItem {
	var backdrop *string
	if it.Backdrop != "" {
		backdrop = &it.Backdrop
	}
	return gen.LibraryItem{
		Id:       it.ID,
		Title:    it.Title,
		Year:     it.Year,
		Type:     gen.MediaType(string(it.Type)),
		Poster:   it.Poster,
		Backdrop: backdrop,
		Overview: it.Overview,
		State:    gen.MediaState(string(it.State)),
	}
}

func (s *Server) GetLibraryIdSeasonsSeasonNumberEpisodes(ctx context.Context, req gen.GetLibraryIdSeasonsSeasonNumberEpisodesRequestObject) (gen.GetLibraryIdSeasonsSeasonNumberEpisodesResponseObject, error) { //nolint:revive // name generated by oapi-codegen
	jfUserID := jfUserIDFromCtx(ctx)

	episodes, err := s.library.GetEpisodes(ctx, jfUserID, req.Id, req.SeasonNumber)
	if err != nil {
		if errors.Is(err, media.ErrItemNotFound) {
			return gen.GetLibraryIdSeasonsSeasonNumberEpisodes404JSONResponse(apiError(ctx, gen.ItemNotFound, "show or season not found")), nil
		}
		return gen.GetLibraryIdSeasonsSeasonNumberEpisodes503JSONResponse(apiError(ctx, gen.BackendUnavailable, "upstream error")), nil
	}

	genEps := make([]gen.Episode, len(episodes))
	for i, ep := range episodes {
		genEps[i] = toGenEpisode(ep)
	}
	return gen.GetLibraryIdSeasonsSeasonNumberEpisodes200JSONResponse(gen.EpisodeListResponse{
		Episodes: genEps,
	}), nil
}

func toGenEpisode(ep media.Episode) gen.Episode {
	e := gen.Episode{
		Id:           ep.ID,
		Number:       ep.Number,
		SeasonNumber: ep.SeasonNumber,
		Title:        ep.Title,
		State:        gen.MediaState(ep.State),
	}
	if ep.Overview != "" {
		e.Overview = &ep.Overview
	}
	if ep.Runtime > 0 {
		e.Runtime = &ep.Runtime
	}
	if ep.Thumbnail != "" {
		e.Thumbnail = &ep.Thumbnail
	}
	if ep.Play != nil {
		e.Play = &gen.PlayInfo{StreamUrl: ep.Play.StreamURL}
	}
	if ep.Progress != nil {
		e.Progress = &gen.WatchProgress{PositionMs: ep.Progress.PositionMS, Played: ep.Progress.Played}
	}
	return e
}

func toGenDetail(d *media.Detail) gen.LibraryDetail {
	base := toGenItem(d.Item)

	cast := make([]gen.CastMember, len(d.Cast))
	for i, c := range d.Cast {
		cast[i] = gen.CastMember{Name: c.Name, Role: c.Role}
	}

	genres := d.Genres
	if genres == nil {
		genres = []string{}
	}

	seasons := make([]gen.Season, len(d.Seasons))
	for i, s := range d.Seasons {
		gs := gen.Season{
			Number:       s.Number,
			Name:         s.Name,
			EpisodeCount: s.EpisodeCount,
			Poster:       s.Poster,
		}
		if s.Year != 0 {
			gs.Year = &s.Year
		}
		seasons[i] = gs
	}

	detail := gen.LibraryDetail{
		Id:       base.Id,
		Title:    base.Title,
		Year:     base.Year,
		Type:     base.Type,
		Poster:   base.Poster,
		Backdrop: base.Backdrop,
		Overview: base.Overview,
		State:    base.State,
		Genres:   genres,
		Runtime:  d.Runtime,
		Cast:     cast,
		Seasons:  seasons,
	}

	if d.Play != nil {
		detail.Play = &gen.PlayInfo{StreamUrl: d.Play.StreamURL}
	}
	if d.Progress != nil {
		detail.Progress = &gen.WatchProgress{
			PositionMs: d.Progress.PositionMS,
			Played:     d.Progress.Played,
		}
	}
	if d.Resume != nil {
		thumbnail := d.Resume.Thumbnail
		detail.Resume = &gen.ResumeInfo{
			SeasonNumber:  d.Resume.SeasonNumber,
			EpisodeNumber: d.Resume.EpisodeNumber,
			EpisodeId:     d.Resume.EpisodeID,
			Title:         d.Resume.Title,
			Thumbnail:     &thumbnail,
			Play:          gen.PlayInfo{StreamUrl: d.Resume.Play.StreamURL},
			Progress:      gen.WatchProgress{PositionMs: d.Resume.Progress.PositionMS, Played: d.Resume.Progress.Played},
		}
	}

	return detail
}

func userIDFromCtx(ctx context.Context) string {
	v, _ := ctx.Value(ctxUserID).(string)
	return v
}

func jfUserIDFromCtx(ctx context.Context) string {
	v, _ := ctx.Value(ctxJFUserID).(string)
	return v
}
