package http

import (
	"context"
	"errors"

	"github.com/Stoganet/api-proxy/internal/gen"
	"github.com/Stoganet/api-proxy/internal/media"
)

func (s *Server) PutPlaybackIdProgress(ctx context.Context, req gen.PutPlaybackIdProgressRequestObject) (gen.PutPlaybackIdProgressResponseObject, error) { //nolint:revive // name generated by oapi-codegen
	jfUserID := jfUserIDFromCtx(ctx)

	if req.Body.PositionMs < 0 {
		return gen.PutPlaybackIdProgress400JSONResponse(apiError(ctx, gen.ValidationFailed, "position_ms must not be negative")), nil
	}

	err := s.library.ReportProgress(ctx, jfUserID, req.Id, req.Body.PositionMs, req.Body.Played)
	if err != nil {
		if errors.Is(err, media.ErrItemNotFound) {
			return gen.PutPlaybackIdProgress404JSONResponse(apiError(ctx, gen.ItemNotFound, "item not found")), nil
		}
		return gen.PutPlaybackIdProgress503JSONResponse(apiError(ctx, gen.BackendUnavailable, "upstream error")), nil
	}

	return gen.PutPlaybackIdProgress204Response{}, nil
}
