package http

import (
	"context"
	"errors"

	"github.com/Stoganet/api-proxy/internal/gen"
	"github.com/Stoganet/api-proxy/internal/media"
)

func (s *Server) GetSearch(ctx context.Context, req gen.GetSearchRequestObject) (gen.GetSearchResponseObject, error) { //nolint:revive // name generated by oapi-codegen
	if req.Params.Q == "" {
		return gen.GetSearch400JSONResponse(apiError(ctx, gen.ValidationFailed, "q must not be empty")), nil
	}

	items, err := s.library.Search(ctx, req.Params.Q)
	if err != nil {
		return gen.GetSearch503JSONResponse(apiError(ctx, gen.BackendUnavailable, "upstream error")), nil //nolint:nilerr // error encoded in response
	}

	genItems := make([]gen.LibraryItem, len(items))
	for i, it := range items {
		genItems[i] = toGenItem(it)
	}
	return gen.GetSearch200JSONResponse(gen.SearchResponse{Items: genItems}), nil
}

func (s *Server) PostLibraryIdRequest(ctx context.Context, req gen.PostLibraryIdRequestRequestObject) (gen.PostLibraryIdRequestResponseObject, error) { //nolint:revive // name generated by oapi-codegen
	err := s.library.RequestMovie(ctx, req.Id)
	if err != nil {
		if errors.Is(err, media.ErrNotRequestable) {
			return gen.PostLibraryIdRequest400JSONResponse(apiError(ctx, gen.ValidationFailed, "not a requestable movie id")), nil
		}
		return gen.PostLibraryIdRequest503JSONResponse(apiError(ctx, gen.BackendUnavailable, "upstream error")), nil //nolint:nilerr // error encoded in response
	}
	return gen.PostLibraryIdRequest204Response{}, nil
}
