package http

import (
	"context"
	"errors"
	"strconv"

	"github.com/Stoganet/api-proxy/internal/catalog"
	"github.com/Stoganet/api-proxy/internal/gen"
)

func (s *Server) GetCatalogId(ctx context.Context, req gen.GetCatalogIdRequestObject) (gen.GetCatalogIdResponseObject, error) { //nolint:revive // name generated by oapi-codegen
	userID := userIDFromCtx(ctx)
	jfUserID := jfUserIDFromCtx(ctx)

	jfTok, err := s.auth.GetJellyfinToken(ctx, userID)
	if err != nil {
		return gen.GetCatalogId503JSONResponse(apiError(ctx, gen.BackendUnavailable, "could not retrieve session")), nil //nolint:nilerr // error encoded in response
	}

	d, err := s.catalog.GetItem(ctx, jfUserID, jfTok, req.Id)
	if err != nil {
		if errors.Is(err, catalog.ErrItemNotFound) {
			return gen.GetCatalogId404JSONResponse(apiError(ctx, gen.ItemNotFound, "item not found")), nil
		}
		return gen.GetCatalogId503JSONResponse(apiError(ctx, gen.BackendUnavailable, "upstream error")), nil
	}

	return gen.GetCatalogId200JSONResponse(toGenDetail(d)), nil
}

func (s *Server) GetCatalog(ctx context.Context, req gen.GetCatalogRequestObject) (gen.GetCatalogResponseObject, error) {
	jfUserID := jfUserIDFromCtx(ctx)

	opts := catalog.ListOpts{}
	if req.Params.Type != nil {
		opts.Type = string(*req.Params.Type)
	}
	if req.Params.Limit != nil {
		opts.Limit = *req.Params.Limit
	}
	if req.Params.Cursor != nil {
		if n, err := strconv.Atoi(*req.Params.Cursor); err == nil {
			opts.StartIndex = n
		}
	}

	result, err := s.catalog.List(ctx, jfUserID, opts)
	if err != nil {
		return gen.GetCatalog503JSONResponse(apiError(ctx, gen.BackendUnavailable, "upstream error")), nil //nolint:nilerr // error encoded in response
	}

	items := make([]gen.CatalogItem, len(result.Items))
	for i, it := range result.Items {
		items[i] = toGenItem(it)
	}

	var nextCursor *string
	if result.NextCursor != "" {
		nextCursor = &result.NextCursor
	}

	return gen.GetCatalog200JSONResponse(gen.CatalogListResponse{
		Items:      items,
		Total:      result.Total,
		NextCursor: nextCursor,
	}), nil
}

func toGenItem(it catalog.Item) gen.CatalogItem {
	var backdrop *string
	if it.Backdrop != "" {
		backdrop = &it.Backdrop
	}
	return gen.CatalogItem{
		Id:       it.ID,
		Title:    it.Title,
		Year:     it.Year,
		Type:     gen.MediaType(it.Type),
		Poster:   it.Poster,
		Backdrop: backdrop,
		Overview: it.Overview,
		State:    gen.MediaState(it.State),
	}
}

func toGenDetail(d *catalog.Detail) gen.CatalogDetail {
	cast := make([]gen.CastMember, len(d.Cast))
	for i, c := range d.Cast {
		cast[i] = gen.CastMember{Name: c.Name, Role: c.Role}
	}

	genres := d.Genres
	if genres == nil {
		genres = []string{}
	}

	var backdrop *string
	if d.Backdrop != "" {
		backdrop = &d.Backdrop
	}

	detail := gen.CatalogDetail{
		Id:       d.ID,
		Title:    d.Title,
		Year:     d.Year,
		Type:     gen.MediaType(d.Type),
		Poster:   d.Poster,
		Backdrop: backdrop,
		Overview: d.Overview,
		State:    gen.MediaState(d.State),
		Genres:   genres,
		Runtime:  d.Runtime,
		Cast:     cast,
		Seasons:  d.Seasons,
	}

	if d.Play != nil {
		detail.Play = &gen.PlayInfo{
			JellyfinItemId:      d.Play.JellyfinItemID,
			JellyfinBaseUrl:     d.Play.JellyfinBaseURL,
			JellyfinAccessToken: d.Play.JellyfinAccessToken,
			JellyfinUserId:      d.Play.JellyfinUserID,
		}
	}

	return detail
}

func userIDFromCtx(ctx context.Context) string {
	v, _ := ctx.Value(ctxUserID).(string)
	return v
}

func jfUserIDFromCtx(ctx context.Context) string {
	v, _ := ctx.Value(ctxJFUserID).(string)
	return v
}
